"""Ported from bpbreid's torchreid/losses/body_part_attention_loss.py. Supervises BPBReID's
pixel-to-part classifier (pixels_cls_scores, from BPBReIDEncoder.forward_full) against PifPaf-
derived ground-truth part masks -- the one loss in this repo that needs masks at all, and
therefore only usable when the dataset in use actually has a masks/ directory on disk (masks
are auto-generated by a pose model, not manually labeled, so using them doesn't reintroduce
identity supervision into an otherwise-unsupervised pipeline).

Deviates from the original in two ways: monai (needed only for the 'fl'/'dl' loss_type variants)
is imported lazily instead of at module level, so the common 'cl' (cross-entropy) path doesn't
require installing it; and accuracy is computed as a plain argmax-equality mean instead of via
torchmetrics.Accuracy, avoiding a dependency on that package's version-specific constructor API.
"""
import torch
import torch.nn as nn


class BodyPartAttentionLoss(nn.Module):
    def __init__(self, loss_type='cl', label_smoothing=0.1):
        super(BodyPartAttentionLoss, self).__init__()
        if loss_type == 'cl':
            self.part_prediction_loss = nn.CrossEntropyLoss(label_smoothing=label_smoothing)
        elif loss_type == 'fl':
            from monai.losses import FocalLoss
            self.part_prediction_loss = FocalLoss(to_onehot_y=True, gamma=1.0)
        elif loss_type == 'dl':
            from monai.losses import DiceLoss
            self.part_prediction_loss = DiceLoss(to_onehot_y=True, softmax=True)
        else:
            raise ValueError('Loss {} for part prediction is not supported'.format(loss_type))

    def forward(self, pixels_cls_scores, targets):
        """pixels_cls_scores: [N, K, H, W]. targets: [N, H, W] (integer part-class index per pixel)."""
        targets = targets.to(pixels_cls_scores.device)
        flat_targets = targets.flatten()  # [N*H*W]
        flat_scores = pixels_cls_scores.permute(0, 2, 3, 1).flatten(0, 2)  # [N*H*W, K]
        loss = self.part_prediction_loss(flat_scores, flat_targets)
        with torch.no_grad():
            accuracy = (flat_scores.argmax(dim=1) == flat_targets).float().mean().item()
        return loss, accuracy
